### ISSUE TITLE
Do templates support IPv6 and Failover?

### ISSUE THREAD

**Issue by vkurenyshev-godaddy** [F5Networks/f5-aws-cloudformation-v2#26]
## Describe the bug
 

Could you advise if these new templates support IPv6 and Failover between AZs?

**Comment by shyawnkarim** [comment]
Yes, these new templates can be used with IPv6.

**Comment by vkurenyshev-godaddy** [comment]
@shyawnkarim thank you.

Could you provide more details on how IPv6 behaves when a failover happens? 
As I understand, Failover is deployed two F5s in different AZs. You use EIP for IPv4 to point to a new AZ, but what about IPv6?

**Comment by shyawnkarim** [comment]
Upon further investigation, the example solutions do not support deploying IPv6. Although the network module supports creating an IPv6 network, the other modules (including BIG-IP) do not do not support deploying IPv6.  

Regarding the failover solution, for reasons mentioned above (i.e. EIPs only for IPv4), CFE only supports IPv6 failover for routes and not addresses.

https://clouddocs.f5.com/products/extensions/f5-cloud-failover/latest/userguide/example-declarations.html#aws-ipv6-route-failover

In order to prioritize and understand the issue better, please reach out to me at s.karim@f5.com.

**Comment by shyawnkarim** [comment]
Closing. Please open another issue if needed.
