### ISSUE TITLE
Failover with BIG-IQ licensing

### ISSUE THREAD

**Issue by PiotrBratkowski** [F5Networks/f5-aws-cloudformation-v2#34]
Hello,

Can you provide example with Failover deployment with licensing from BIG-IQ?

Regards,
Piotr Bratkowski

**Comment by mikeshimkus** [comment]
Hi @PiotrBratkowski, there are currently no plans to publish a failover example that licenses the BIG-IP instances via BIG-IQ. I can describe the process of customizing the runtime init configuration/template if that would be helpful to you.
thanks

**Comment by PiotrBratkowski** [comment]
Hello @mikeshimkus I've already did it. Almost, it gets license, but cluster is not forming, which is strange as I'm using basically parts of failover configuration. Maybe you can look and tell me if you see something missing/wrong with this. Additionally I don't understand why DO is done twice. If you can describe this process that would be helpful also.
[runtime-init-conf-3nic-bigiq-1.txt](https://github.com/F5Networks/f5-aws-cloudformation-v2/files/11155743/runtime-init-conf-3nic-bigiq-1.txt)

**Comment by mikeshimkus** [comment]
DO runs twice because of a race condition due to the unpredictability of which device will boot up first; the cluster config must be created last on both devices to prevent sync issues.

About the clustering in your case, I see that you are pointing to local files to get both secret values (for BIG-IP and BIG-IQ password) but by default, the bigip module only supports a single secret passed from the template: https://github.com/F5Networks/f5-aws-cloudformation-v2/blob/a4d715d3c22fed7d779e1cd693c008636a464672/examples/modules/bigip-standalone/bigip-standalone.yaml#L1225

Did you also customize the bigip template to support an extra secret? Also, can you share the output of /var/log/cloud/startup-script.log?
thanks
